#!/usr/bin/fish

# import $DYNDNS_IP
if not source ./secret
    exit 1
end

# install fisher (https://github.com/jorgebucaran/fisher)
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

# install nvm (https://github.com/jorgebucaran/nvm.fish)
fisher install jorgebucaran/nvm.fish
nvm install lts
nvm use lts
set --universal nvm_default_version lts

# pretty listing
alias --save ll='ls -hAlF'

# connect to the raspberry pi
alias --save sshpi="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null pi@\$(curl -s $DYNDNS_URL)"

# change default shell
echo 'Enter sudo password for setting fish as default shell:'
chsh -s (command -s fish)
